"""empty message

Revision ID: 075fb3f971ea
Revises: 3dce3eff51c9
Create Date: 2021-05-17 19:05:41.367838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075fb3f971ea'
down_revision = '3dce3eff51c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ban_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_banned')
        batch_op.drop_column('ban_reason')

    # ### end Alembic commands ###
