"""empty message

Revision ID: 11674f18db38
Revises: c4fb002dfbba
Create Date: 2021-05-15 04:22:09.792839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11674f18db38'
down_revision = 'c4fb002dfbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_request', schema=None) as batch_op:
        batch_op.drop_column('checked')

    # ### end Alembic commands ###
