"""empty message

Revision ID: 3dce3eff51c9
Revises: 11674f18db38
Create Date: 2021-05-15 05:04:14.039136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dce3eff51c9'
down_revision = '11674f18db38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_request', schema=None) as batch_op:
        batch_op.drop_column('checked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
