"""empty message

Revision ID: 5768ca49c73c
Revises: 9c8df1b12e68
Create Date: 2021-05-09 20:31:26.100052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5768ca49c73c'
down_revision = '9c8df1b12e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['user.id'], name=op.f('fk_edit_request_editor_id_user')),
    sa.ForeignKeyConstraint(['target_id'], ['discussion.id'], name=op.f('fk_edit_request_target_id_discussion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edit_request')),
    sa.UniqueConstraint('text', name=op.f('uq_edit_request_text'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edit_request')
    # ### end Alembic commands ###
