"""empty message

Revision ID: 66df75833aab
Revises: 6253ead8b34a
Create Date: 2021-05-14 02:33:20.465355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66df75833aab'
down_revision = '6253ead8b34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('register_date')

    # ### end Alembic commands ###
