"""empty message

Revision ID: 8d75e7f11862
Revises: adc8654354f8
Create Date: 2021-05-08 04:52:58.037743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d75e7f11862'
down_revision = 'adc8654354f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_discussion_text'), ['text'])

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_section_description'), ['description'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_section_description'), type_='unique')
        batch_op.drop_column('description')

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_discussion_text'), type_='unique')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
