"""empty message

Revision ID: d667133d57dd
Revises: 9e02980339d8
Create Date: 2021-05-19 00:06:43.767634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd667133d57dd'
down_revision = '9e02980339d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_validated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_request', schema=None) as batch_op:
        batch_op.drop_column('is_validated')

    # ### end Alembic commands ###
