"""empty message

Revision ID: f748973e0bff
Revises: 8f0cf716bbf3
Create Date: 2021-05-07 21:57:42.399635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f748973e0bff'
down_revision = '8f0cf716bbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name=op.f('fk_tag_section_id_section')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('discussion_tags',
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.id'], name=op.f('fk_discussion_tags_discussion_id_discussion')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_discussion_tags_tag_id_tag'))
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_image_name'), ['name'])
        batch_op.drop_constraint('uq_image_path', type_='unique')
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), nullable=False))
        batch_op.create_unique_constraint('uq_image_path', ['path'])
        batch_op.drop_constraint(batch_op.f('uq_image_name'), type_='unique')
        batch_op.drop_column('name')

    op.drop_table('discussion_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
